# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\24352\Desktop\src\face_identify\登录.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(439, 656)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        Form.setFont(font)
        Form.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        Form.setAutoFillBackground(True)
        Form.setStyleSheet("")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(-10, 0, 461, 661))
        self.label.setStyleSheet("image: url(tafei.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(340, 610, 91, 41))
        self.pushButton.setStyleSheet("background-color: rgba(243, 239, 255, 200);\n"
"font: 12pt \"Arial\";")
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(270, 40, 151, 61))
        self.label_2.setStyleSheet("font: 75 12pt \"Arial\";\n"
"")
        self.label_2.setScaledContents(False)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(-10, 590, 451, 71))
        self.lineEdit.setStyleSheet("background-color: rgba(248, 115, 152, 180);\n"
"font: 16pt \"Arial\";")
        self.lineEdit.setText("")
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(250, 30, 191, 111))
        self.label_3.setStyleSheet("image: url(qipao.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label.raise_()
        self.label_3.raise_()
        self.lineEdit.raise_()
        self.pushButton.raise_()
        self.label_2.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "身份认证"))
        self.pushButton.setText(_translate("Form", "确认"))
        self.label_2.setText(_translate("Form", "学号多少？"))
